language: node_js
node_js:
  - 16
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
before_deploy:
  - echo "FUCK!"
  # - cp -r ./docs/.vitepress/doc/rune_doc ./docs/.vitepress/dist
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
